export enum CHROME_COMMAND_ENUM {
  OPEN_SIDE_PANEL_APP = 'openSidePanel',
  SCRAP_CURRENT_TAB = 'scrapCurrentTab',
}

export type ChromeCommandType =
  | CHROME_COMMAND_ENUM.OPEN_SIDE_PANEL_APP
  | CHROME_COMMAND_ENUM.SCRAP_CURRENT_TAB;
