export enum CHROME_COMMAND_ENUM {
  OPEN_SIDE_PANEL_APP = 'openSidePanel',
  SCRAPE_CURRENT_TAB = 'scrapCurrentTab',
  GET_ACTIVE_TAB = 'getActiveTab',
  BASE_SEO_AUDIT = 'baseSeoAudit',
  HIGHLIGHT_HEADERS = 'highlightHeaders',
  PARSE_HEADINGS = 'parseHeadings',
  SCROLL_TO_HEADING = 'scrollToHeading',
  COLLECT_WEB_VITALS = 'collectWebVitals',
}

export type ChromeCommandType =
  | CHROME_COMMAND_ENUM.OPEN_SIDE_PANEL_APP
  | CHROME_COMMAND_ENUM.GET_ACTIVE_TAB
  | CHROME_COMMAND_ENUM.SCRAPE_CURRENT_TAB
  | CHROME_COMMAND_ENUM.BASE_SEO_AUDIT
  | CHROME_COMMAND_ENUM.HIGHLIGHT_HEADERS
  | CHROME_COMMAND_ENUM.PARSE_HEADINGS
  | CHROME_COMMAND_ENUM.SCROLL_TO_HEADING
  | CHROME_COMMAND_ENUM.COLLECT_WEB_VITALS;

/** Keepalive port name between side panel and background */
export const CHROME_KEEPALIVE_PORT = 'dz-keepalive';
