export enum CHROME_COMMAND_ENUM {
  SCRAPE_CURRENT_TAB = 'scrapCurrentTab',
  GET_ACTIVE_TAB = 'getActiveTab',
  BASE_SEO_AUDIT = 'baseSeoAudit',
  HIGHLIGHT_HEADERS = 'highlightHeaders',
  PARSE_HEADINGS = 'parseHeadings',
  SCROLL_TO_HEADING = 'scrollToHeading',
  COLLECT_WEB_VITALS = 'collectWebVitals',
  COLLECT_WEB_VITALS_BOTH = 'collectWebVitalsBoth',
  CLOSE_PANEL = 'closePanel',
  COLLECT_SCHEMA_OG = 'collectSchemaOg',
  ANALYZE_CONTENT = 'analyzeContent',
}

export type ChromeCommandType =
  | CHROME_COMMAND_ENUM.GET_ACTIVE_TAB
  | CHROME_COMMAND_ENUM.SCRAPE_CURRENT_TAB
  | CHROME_COMMAND_ENUM.BASE_SEO_AUDIT
  | CHROME_COMMAND_ENUM.HIGHLIGHT_HEADERS
  | CHROME_COMMAND_ENUM.PARSE_HEADINGS
  | CHROME_COMMAND_ENUM.SCROLL_TO_HEADING
  | CHROME_COMMAND_ENUM.COLLECT_WEB_VITALS
  | CHROME_COMMAND_ENUM.COLLECT_WEB_VITALS_BOTH
  | CHROME_COMMAND_ENUM.COLLECT_SCHEMA_OG
  | CHROME_COMMAND_ENUM.ANALYZE_CONTENT;

/** Keepalive port name between panel iframe and background */
export const CHROME_KEEPALIVE_PORT = 'dz-keepalive';
